language: c

compiler: gcc

env:
    global:
        - USE_CCACHE=1

build:
    cache: true

    ci:
      - sudo apt-get install doxygen make
      - sudo pip install breathe sphinx awscli sphinx_rtd_theme
      - rm -rf themes/zephyr-docs-theme
      - git clone https://github.com/zephyrproject-rtos/docs-theme.git themes/zephyr-docs-theme
      - make html

integrations:
  notifications:
    - integrationName: slack_integration
      type: slack
      recipients:
        - "#ci"
      branches:
        only:
          - master
      on_success: never
      on_failure: always
    - integrationName: email
      type: email
      recipients:
        - builds@zephyrproject.org
      branches:
        only:
          - master
          - net
          - bluetooth
          - arm
      on_success: never
      on_failure: never
